// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/node_agent/v1/node_agent.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_DEFAULT     CommandType = 0
	CommandType_COMMAND_TYPE_CUSTOM      CommandType = 1
	CommandType_COMMAND_TYPE_INSTALL_APP CommandType = 2
	CommandType_COMMAND_TYPE_SWARM       CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_DEFAULT",
		1: "COMMAND_TYPE_CUSTOM",
		2: "COMMAND_TYPE_INSTALL_APP",
		3: "COMMAND_TYPE_SWARM",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_DEFAULT":     0,
		"COMMAND_TYPE_CUSTOM":      1,
		"COMMAND_TYPE_INSTALL_APP": 2,
		"COMMAND_TYPE_SWARM":       3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_agent_v1_node_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_node_agent_v1_node_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

// ProfileType selects what the agent should sample.
type ProfileType int32

const (
	ProfileType_PROFILE_TYPE_HEAP ProfileType = 0 // Heap / memory allocation snapshot (instantaneous)
	ProfileType_PROFILE_TYPE_CPU  ProfileType = 1 // CPU sampling for duration_seconds
)

// Enum value maps for ProfileType.
var (
	ProfileType_name = map[int32]string{
		0: "PROFILE_TYPE_HEAP",
		1: "PROFILE_TYPE_CPU",
	}
	ProfileType_value = map[string]int32{
		"PROFILE_TYPE_HEAP": 0,
		"PROFILE_TYPE_CPU":  1,
	}
)

func (x ProfileType) Enum() *ProfileType {
	p := new(ProfileType)
	*p = x
	return p
}

func (x ProfileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_agent_v1_node_agent_proto_enumTypes[1].Descriptor()
}

func (ProfileType) Type() protoreflect.EnumType {
	return &file_proto_node_agent_v1_node_agent_proto_enumTypes[1]
}

func (x ProfileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileType.Descriptor instead.
func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 0
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 1
	JobStatus_JOB_STATUS_FAILED    JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_RUNNING",
		1: "JOB_STATUS_COMPLETED",
		2: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_RUNNING":   0,
		"JOB_STATUS_COMPLETED": 1,
		"JOB_STATUS_FAILED":    2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_agent_v1_node_agent_proto_enumTypes[2].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_node_agent_v1_node_agent_proto_enumTypes[2]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{2}
}

type RegisterCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // validated against the auth token server-side
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          CommandType            `protobuf:"varint,4,opt,name=type,proto3,enum=node_agent.v1.CommandType" json:"type,omitempty"`
	ScriptPath    string                 `protobuf:"bytes,5,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"` // only set for COMMAND_TYPE_CUSTOM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandRequest) Reset() {
	*x = RegisterCommandRequest{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandRequest) ProtoMessage() {}

func (x *RegisterCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCommandRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCommandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterCommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

func (x *RegisterCommandRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

type RegisterCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    int32                  `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"` // total commands upserted in this batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandsResponse) Reset() {
	*x = RegisterCommandsResponse{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandsResponse) ProtoMessage() {}

func (x *RegisterCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandsResponse.ProtoReflect.Descriptor instead.
func (*RegisterCommandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCommandsResponse) GetRegistered() int32 {
	if x != nil {
		return x.Registered
	}
	return 0
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_JobResult
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_LogEntry
	//	*NodeMessage_Metric
	//	*NodeMessage_HealthResult
	//	*NodeMessage_ProfileData
	//	*NodeMessage_ContainerList
	//	*NodeMessage_LogDiagnostic
	//	*NodeMessage_NetworkStats
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetJobResult() *JobResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *HeartbeatPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetLogEntry() *LogEntryPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

func (x *NodeMessage) GetMetric() *MetricPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *NodeMessage) GetHealthResult() *HealthCheckResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_HealthResult); ok {
			return x.HealthResult
		}
	}
	return nil
}

func (x *NodeMessage) GetProfileData() *ProfileDataPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ProfileData); ok {
			return x.ProfileData
		}
	}
	return nil
}

func (x *NodeMessage) GetContainerList() *ContainerListPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ContainerList); ok {
			return x.ContainerList
		}
	}
	return nil
}

func (x *NodeMessage) GetLogDiagnostic() *LogDiagnosticPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_LogDiagnostic); ok {
			return x.LogDiagnostic
		}
	}
	return nil
}

func (x *NodeMessage) GetNetworkStats() *NetworkStatsPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_NetworkStats); ok {
			return x.NetworkStats
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_JobResult struct {
	JobResult *JobResultPayload `protobuf:"bytes,1,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *HeartbeatPayload `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_LogEntry struct {
	LogEntry *LogEntryPayload `protobuf:"bytes,3,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

type NodeMessage_Metric struct {
	Metric *MetricPayload `protobuf:"bytes,4,opt,name=metric,proto3,oneof"`
}

type NodeMessage_HealthResult struct {
	HealthResult *HealthCheckResultPayload `protobuf:"bytes,5,opt,name=health_result,json=healthResult,proto3,oneof"`
}

type NodeMessage_ProfileData struct {
	ProfileData *ProfileDataPayload `protobuf:"bytes,6,opt,name=profile_data,json=profileData,proto3,oneof"`
}

type NodeMessage_ContainerList struct {
	ContainerList *ContainerListPayload `protobuf:"bytes,7,opt,name=container_list,json=containerList,proto3,oneof"`
}

type NodeMessage_LogDiagnostic struct {
	LogDiagnostic *LogDiagnosticPayload `protobuf:"bytes,8,opt,name=log_diagnostic,json=logDiagnostic,proto3,oneof"`
}

type NodeMessage_NetworkStats struct {
	NetworkStats *NetworkStatsPayload `protobuf:"bytes,9,opt,name=network_stats,json=networkStats,proto3,oneof"`
}

func (*NodeMessage_JobResult) isNodeMessage_Payload() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Payload() {}

func (*NodeMessage_LogEntry) isNodeMessage_Payload() {}

func (*NodeMessage_Metric) isNodeMessage_Payload() {}

func (*NodeMessage_HealthResult) isNodeMessage_Payload() {}

func (*NodeMessage_ProfileData) isNodeMessage_Payload() {}

func (*NodeMessage_ContainerList) isNodeMessage_Payload() {}

func (*NodeMessage_LogDiagnostic) isNodeMessage_Payload() {}

func (*NodeMessage_NetworkStats) isNodeMessage_Payload() {}

type MetricPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamTotalBytes      uint64                 `protobuf:"varint,2,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	RamUsedBytes       uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamAvailableBytes  uint64                 `protobuf:"varint,4,opt,name=ram_available_bytes,json=ramAvailableBytes,proto3" json:"ram_available_bytes,omitempty"`
	RamUsagePercent    float32                `protobuf:"fixed32,5,opt,name=ram_usage_percent,json=ramUsagePercent,proto3" json:"ram_usage_percent,omitempty"`
	DiskTotalBytes     uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes      uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskAvailableBytes uint64                 `protobuf:"varint,8,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`
	DiskUsagePercent   float32                `protobuf:"fixed32,9,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *MetricPayload) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MetricPayload) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MetricPayload) GetRamAvailableBytes() uint64 {
	if x != nil {
		return x.RamAvailableBytes
	}
	return 0
}

func (x *MetricPayload) GetRamUsagePercent() float32 {
	if x != nil {
		return x.RamUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_ExecuteJob
	//	*ServerMessage_StreamLogs
	//	*ServerMessage_StopLogs
	//	*ServerMessage_ConfigureHealthCheck
	//	*ServerMessage_StopHealthCheck
	//	*ServerMessage_RequestProfile
	//	*ServerMessage_StreamContainers
	//	*ServerMessage_StopContainers
	//	*ServerMessage_CollectLogs
	//	*ServerMessage_RequestNetworkStats
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetExecuteJob() *ExecuteJobPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteJob); ok {
			return x.ExecuteJob
		}
	}
	return nil
}

func (x *ServerMessage) GetStreamLogs() *StreamLogsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StreamLogs); ok {
			return x.StreamLogs
		}
	}
	return nil
}

func (x *ServerMessage) GetStopLogs() *StopLogsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StopLogs); ok {
			return x.StopLogs
		}
	}
	return nil
}

func (x *ServerMessage) GetConfigureHealthCheck() *ConfigureHealthCheckPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ConfigureHealthCheck); ok {
			return x.ConfigureHealthCheck
		}
	}
	return nil
}

func (x *ServerMessage) GetStopHealthCheck() *StopHealthCheckPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StopHealthCheck); ok {
			return x.StopHealthCheck
		}
	}
	return nil
}

func (x *ServerMessage) GetRequestProfile() *RequestProfilePayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RequestProfile); ok {
			return x.RequestProfile
		}
	}
	return nil
}

func (x *ServerMessage) GetStreamContainers() *StreamContainersPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StreamContainers); ok {
			return x.StreamContainers
		}
	}
	return nil
}

func (x *ServerMessage) GetStopContainers() *StopContainersPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StopContainers); ok {
			return x.StopContainers
		}
	}
	return nil
}

func (x *ServerMessage) GetCollectLogs() *CollectLogsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CollectLogs); ok {
			return x.CollectLogs
		}
	}
	return nil
}

func (x *ServerMessage) GetRequestNetworkStats() *RequestNetworkStatsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RequestNetworkStats); ok {
			return x.RequestNetworkStats
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_ExecuteJob struct {
	ExecuteJob *ExecuteJobPayload `protobuf:"bytes,1,opt,name=execute_job,json=executeJob,proto3,oneof"`
}

type ServerMessage_StreamLogs struct {
	StreamLogs *StreamLogsPayload `protobuf:"bytes,2,opt,name=stream_logs,json=streamLogs,proto3,oneof"`
}

type ServerMessage_StopLogs struct {
	StopLogs *StopLogsPayload `protobuf:"bytes,3,opt,name=stop_logs,json=stopLogs,proto3,oneof"`
}

type ServerMessage_ConfigureHealthCheck struct {
	ConfigureHealthCheck *ConfigureHealthCheckPayload `protobuf:"bytes,4,opt,name=configure_health_check,json=configureHealthCheck,proto3,oneof"`
}

type ServerMessage_StopHealthCheck struct {
	StopHealthCheck *StopHealthCheckPayload `protobuf:"bytes,5,opt,name=stop_health_check,json=stopHealthCheck,proto3,oneof"`
}

type ServerMessage_RequestProfile struct {
	RequestProfile *RequestProfilePayload `protobuf:"bytes,6,opt,name=request_profile,json=requestProfile,proto3,oneof"`
}

type ServerMessage_StreamContainers struct {
	StreamContainers *StreamContainersPayload `protobuf:"bytes,7,opt,name=stream_containers,json=streamContainers,proto3,oneof"`
}

type ServerMessage_StopContainers struct {
	StopContainers *StopContainersPayload `protobuf:"bytes,8,opt,name=stop_containers,json=stopContainers,proto3,oneof"`
}

type ServerMessage_CollectLogs struct {
	CollectLogs *CollectLogsPayload `protobuf:"bytes,9,opt,name=collect_logs,json=collectLogs,proto3,oneof"`
}

type ServerMessage_RequestNetworkStats struct {
	RequestNetworkStats *RequestNetworkStatsPayload `protobuf:"bytes,10,opt,name=request_network_stats,json=requestNetworkStats,proto3,oneof"`
}

func (*ServerMessage_ExecuteJob) isServerMessage_Payload() {}

func (*ServerMessage_StreamLogs) isServerMessage_Payload() {}

func (*ServerMessage_StopLogs) isServerMessage_Payload() {}

func (*ServerMessage_ConfigureHealthCheck) isServerMessage_Payload() {}

func (*ServerMessage_StopHealthCheck) isServerMessage_Payload() {}

func (*ServerMessage_RequestProfile) isServerMessage_Payload() {}

func (*ServerMessage_StreamContainers) isServerMessage_Payload() {}

func (*ServerMessage_StopContainers) isServerMessage_Payload() {}

func (*ServerMessage_CollectLogs) isServerMessage_Payload() {}

func (*ServerMessage_RequestNetworkStats) isServerMessage_Payload() {}

type JobResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=node_agent.v1.JobStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultPayload) Reset() {
	*x = JobResultPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultPayload) ProtoMessage() {}

func (x *JobResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultPayload.ProtoReflect.Descriptor instead.
func (*JobResultPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{5}
}

func (x *JobResultPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultPayload) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_RUNNING
}

func (x *JobResultPayload) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResultPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ExecuteJobPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandType   CommandType            `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=node_agent.v1.CommandType" json:"command_type,omitempty"`
	Params        string                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // JSON-encoded parameters (e.g. for INSTALL_APP)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobPayload) Reset() {
	*x = ExecuteJobPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobPayload) ProtoMessage() {}

func (x *ExecuteJobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobPayload.ProtoReflect.Descriptor instead.
func (*ExecuteJobPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteJobPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

func (x *ExecuteJobPayload) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

// Sent by server to ask the agent to start streaming logs.
type StreamLogsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`    // systemd unit name, e.g. "autohost-agent" or "" for all
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"` // how many historical lines to tail first (0 = no history)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsPayload) Reset() {
	*x = StreamLogsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsPayload) ProtoMessage() {}

func (x *StreamLogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsPayload.ProtoReflect.Descriptor instead.
func (*StreamLogsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StreamLogsPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *StreamLogsPayload) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

// Sent by server to ask the agent to stop streaming logs.
type StopLogsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLogsPayload) Reset() {
	*x = StopLogsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLogsPayload) ProtoMessage() {}

func (x *StopLogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLogsPayload.ProtoReflect.Descriptor instead.
func (*StopLogsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{9}
}

// Sent by agent to the server, one per log line.
type LogEntryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUs   int64                  `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"` // Unix microseconds
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`                                   // source systemd unit
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryPayload) Reset() {
	*x = LogEntryPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryPayload) ProtoMessage() {}

func (x *LogEntryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryPayload.ProtoReflect.Descriptor instead.
func (*LogEntryPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntryPayload) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *LogEntryPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogEntryPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent by the server to configure or update a health check on the agent.
type ConfigureHealthCheckPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MonitorId          string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	ServiceName        string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CheckType          string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // "process" | "tcp" | "http"
	HttpUrl            string                 `protobuf:"bytes,4,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	HttpExpectedStatus int32                  `protobuf:"varint,5,opt,name=http_expected_status,json=httpExpectedStatus,proto3" json:"http_expected_status,omitempty"`
	TcpHost            string                 `protobuf:"bytes,6,opt,name=tcp_host,json=tcpHost,proto3" json:"tcp_host,omitempty"`
	TcpPort            int32                  `protobuf:"varint,7,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	IntervalSeconds    int32                  `protobuf:"varint,8,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	FailureThreshold   int32                  `protobuf:"varint,9,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	Enabled            bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AutoHealConfig     string                 `protobuf:"bytes,11,opt,name=auto_heal_config,json=autoHealConfig,proto3" json:"auto_heal_config,omitempty"` // JSON string of AutoHealConfig
	AutoHealState      string                 `protobuf:"bytes,12,opt,name=auto_heal_state,json=autoHealState,proto3" json:"auto_heal_state,omitempty"`    // JSON string of ServiceHealthState
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigureHealthCheckPayload) Reset() {
	*x = ConfigureHealthCheckPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureHealthCheckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureHealthCheckPayload) ProtoMessage() {}

func (x *ConfigureHealthCheckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureHealthCheckPayload.ProtoReflect.Descriptor instead.
func (*ConfigureHealthCheckPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureHealthCheckPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetHttpExpectedStatus() int32 {
	if x != nil {
		return x.HttpExpectedStatus
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetTcpHost() string {
	if x != nil {
		return x.TcpHost
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConfigureHealthCheckPayload) GetAutoHealConfig() string {
	if x != nil {
		return x.AutoHealConfig
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetAutoHealState() string {
	if x != nil {
		return x.AutoHealState
	}
	return ""
}

// Sent by the server to remove a health check from the agent.
type StopHealthCheckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopHealthCheckPayload) Reset() {
	*x = StopHealthCheckPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHealthCheckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHealthCheckPayload) ProtoMessage() {}

func (x *StopHealthCheckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHealthCheckPayload.ProtoReflect.Descriptor instead.
func (*StopHealthCheckPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StopHealthCheckPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

// Sent by the agent after each health check execution.
type HealthCheckResultPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MonitorId           string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "up" | "down"
	LatencyMs           int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,5,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	AutoHealState       string                 `protobuf:"bytes,6,opt,name=auto_heal_state,json=autoHealState,proto3" json:"auto_heal_state,omitempty"` // JSON string of updated ServiceHealthState
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckResultPayload) Reset() {
	*x = HealthCheckResultPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResultPayload) ProtoMessage() {}

func (x *HealthCheckResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResultPayload.ProtoReflect.Descriptor instead.
func (*HealthCheckResultPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResultPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *HealthCheckResultPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResultPayload) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthCheckResultPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResultPayload) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *HealthCheckResultPayload) GetAutoHealState() string {
	if x != nil {
		return x.AutoHealState
	}
	return ""
}

// Sent by server to ask the agent to collect a pprof profile.
type RequestProfilePayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlation ID (UUID)
	ProfileType     ProfileType            `protobuf:"varint,2,opt,name=profile_type,json=profileType,proto3,enum=node_agent.v1.ProfileType" json:"profile_type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // only relevant for PROFILE_TYPE_CPU (0 → 30 s default)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestProfilePayload) Reset() {
	*x = RequestProfilePayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProfilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProfilePayload) ProtoMessage() {}

func (x *RequestProfilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProfilePayload.ProtoReflect.Descriptor instead.
func (*RequestProfilePayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{14}
}

func (x *RequestProfilePayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestProfilePayload) GetProfileType() ProfileType {
	if x != nil {
		return x.ProfileType
	}
	return ProfileType_PROFILE_TYPE_HEAP
}

func (x *RequestProfilePayload) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// Sent by agent to deliver the raw pprof bytes back to the server.
type ProfileDataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // matches RequestProfilePayload.request_id
	ProfileType   ProfileType            `protobuf:"varint,2,opt,name=profile_type,json=profileType,proto3,enum=node_agent.v1.ProfileType" json:"profile_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`   // raw pprof binary (pprof.WriteHeapProfile / StopCPUProfile output)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // non-empty when collection failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileDataPayload) Reset() {
	*x = ProfileDataPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDataPayload) ProtoMessage() {}

func (x *ProfileDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDataPayload.ProtoReflect.Descriptor instead.
func (*ProfileDataPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ProfileDataPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProfileDataPayload) GetProfileType() ProfileType {
	if x != nil {
		return x.ProfileType
	}
	return ProfileType_PROFILE_TYPE_HEAP
}

func (x *ProfileDataPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProfileDataPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Sent by server to ask the agent to start streaming container state snapshots.
type StreamContainersPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainersPayload) Reset() {
	*x = StreamContainersPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainersPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainersPayload) ProtoMessage() {}

func (x *StreamContainersPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainersPayload.ProtoReflect.Descriptor instead.
func (*StreamContainersPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{16}
}

// Sent by server to ask the agent to stop streaming container state.
type StopContainersPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainersPayload) Reset() {
	*x = StopContainersPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainersPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainersPayload) ProtoMessage() {}

func (x *StopContainersPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainersPayload.ProtoReflect.Descriptor instead.
func (*StopContainersPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{17}
}

// One Docker container entry within a ContainerListPayload snapshot.
type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                    // "running" | "exited" | "paused" | "restarting" | …
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                  // human-readable, e.g. "Up 2 hours"
	Cpu           string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`                        // CPU usage percentage string (only for running containers)
	Mem           string                 `protobuf:"bytes,7,opt,name=mem,proto3" json:"mem,omitempty"`                        // memory usage/limit string (only for running containers)
	MemPerc       string                 `protobuf:"bytes,8,opt,name=mem_perc,json=memPerc,proto3" json:"mem_perc,omitempty"` // memory percentage string (only for running containers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ContainerInfo) GetMem() string {
	if x != nil {
		return x.Mem
	}
	return ""
}

func (x *ContainerInfo) GetMemPerc() string {
	if x != nil {
		return x.MemPerc
	}
	return ""
}

// Full container list snapshot sent by the agent whenever the list changes.
type ContainerListPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty when Docker is unavailable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerListPayload) Reset() {
	*x = ContainerListPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListPayload) ProtoMessage() {}

func (x *ContainerListPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerListPayload.ProtoReflect.Descriptor instead.
func (*ContainerListPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ContainerListPayload) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *ContainerListPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetricRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamTotalBytes      uint64                 `protobuf:"varint,2,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	RamUsedBytes       uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamAvailableBytes  uint64                 `protobuf:"varint,4,opt,name=ram_available_bytes,json=ramAvailableBytes,proto3" json:"ram_available_bytes,omitempty"`
	RamUsagePercent    float32                `protobuf:"fixed32,5,opt,name=ram_usage_percent,json=ramUsagePercent,proto3" json:"ram_usage_percent,omitempty"`
	DiskTotalBytes     uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes      uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskAvailableBytes uint64                 `protobuf:"varint,8,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`
	DiskUsagePercent   float32                `protobuf:"fixed32,9,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{20}
}

func (x *MetricRequest) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MetricRequest) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MetricRequest) GetRamAvailableBytes() uint64 {
	if x != nil {
		return x.RamAvailableBytes
	}
	return 0
}

func (x *MetricRequest) GetRamUsagePercent() float32 {
	if x != nil {
		return x.RamUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{21}
}

func (x *MetricResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Server asks agent to collect, sanitize and prepare a diagnostic log bundle.
type CollectLogsPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                          // correlation UUID
	Sources           []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`                                               // e.g. ["autohost-agent", "docker:nginx"]
	LinesPerSource    int32                  `protobuf:"varint,3,opt,name=lines_per_source,json=linesPerSource,proto3" json:"lines_per_source,omitempty"`        // max lines per source (default 200, max 500)
	IncludeContainers bool                   `protobuf:"varint,4,opt,name=include_containers,json=includeContainers,proto3" json:"include_containers,omitempty"` // also collect all running container logs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CollectLogsPayload) Reset() {
	*x = CollectLogsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLogsPayload) ProtoMessage() {}

func (x *CollectLogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLogsPayload.ProtoReflect.Descriptor instead.
func (*CollectLogsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CollectLogsPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CollectLogsPayload) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CollectLogsPayload) GetLinesPerSource() int32 {
	if x != nil {
		return x.LinesPerSource
	}
	return 0
}

func (x *CollectLogsPayload) GetIncludeContainers() bool {
	if x != nil {
		return x.IncludeContainers
	}
	return false
}

// Agent returns sanitized logs + local pattern analysis to the server.
type LogDiagnosticPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // correlation UUID
	DiagnosticJson string                 `protobuf:"bytes,2,opt,name=diagnostic_json,json=diagnosticJson,proto3" json:"diagnostic_json,omitempty"` // full JSON diagnostic report
	Sources        []*LogSourceBundle     `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`                                     // raw sanitized log bundles
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                         // non-empty if collection failed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogDiagnosticPayload) Reset() {
	*x = LogDiagnosticPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogDiagnosticPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogDiagnosticPayload) ProtoMessage() {}

func (x *LogDiagnosticPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogDiagnosticPayload.ProtoReflect.Descriptor instead.
func (*LogDiagnosticPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{23}
}

func (x *LogDiagnosticPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogDiagnosticPayload) GetDiagnosticJson() string {
	if x != nil {
		return x.DiagnosticJson
	}
	return ""
}

func (x *LogDiagnosticPayload) GetSources() []*LogSourceBundle {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *LogDiagnosticPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// One log source within a diagnostic bundle.
type LogSourceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                  // e.g. "journalctl:autohost-agent" or "docker:nginx"
	RawLogs       string                 `protobuf:"bytes,2,opt,name=raw_logs,json=rawLogs,proto3" json:"raw_logs,omitempty"` // sanitized log text
	LineCount     int32                  `protobuf:"varint,3,opt,name=line_count,json=lineCount,proto3" json:"line_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSourceBundle) Reset() {
	*x = LogSourceBundle{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSourceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSourceBundle) ProtoMessage() {}

func (x *LogSourceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSourceBundle.ProtoReflect.Descriptor instead.
func (*LogSourceBundle) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{24}
}

func (x *LogSourceBundle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogSourceBundle) GetRawLogs() string {
	if x != nil {
		return x.RawLogs
	}
	return ""
}

func (x *LogSourceBundle) GetLineCount() int32 {
	if x != nil {
		return x.LineCount
	}
	return 0
}

type RequestNetworkStatsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNetworkStatsPayload) Reset() {
	*x = RequestNetworkStatsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNetworkStatsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNetworkStatsPayload) ProtoMessage() {}

func (x *RequestNetworkStatsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNetworkStatsPayload.ProtoReflect.Descriptor instead.
func (*RequestNetworkStatsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{25}
}

func (x *RequestNetworkStatsPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NetworkStatsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatsJson     string                 `protobuf:"bytes,2,opt,name=stats_json,json=statsJson,proto3" json:"stats_json,omitempty"` // JSON-encoded IngestPayload
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatsPayload) Reset() {
	*x = NetworkStatsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatsPayload) ProtoMessage() {}

func (x *NetworkStatsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatsPayload.ProtoReflect.Descriptor instead.
func (*NetworkStatsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{26}
}

func (x *NetworkStatsPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NetworkStatsPayload) GetStatsJson() string {
	if x != nil {
		return x.StatsJson
	}
	return ""
}

func (x *NetworkStatsPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_node_agent_v1_node_agent_proto protoreflect.FileDescriptor

const file_proto_node_agent_v1_node_agent_proto_rawDesc = "" +
	"\n" +
	"$proto/node_agent/v1/node_agent.proto\x12\rnode_agent.v1\"\xb8\x01\n" +
	"\x16RegisterCommandRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\x04type\x12\x1f\n" +
	"\vscript_path\x18\x05 \x01(\tR\n" +
	"scriptPath\":\n" +
	"\x18RegisterCommandsResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\x05R\n" +
	"registered\"\x91\x05\n" +
	"\vNodeMessage\x12@\n" +
	"\n" +
	"job_result\x18\x01 \x01(\v2\x1f.node_agent.v1.JobResultPayloadH\x00R\tjobResult\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.node_agent.v1.HeartbeatPayloadH\x00R\theartbeat\x12=\n" +
	"\tlog_entry\x18\x03 \x01(\v2\x1e.node_agent.v1.LogEntryPayloadH\x00R\blogEntry\x126\n" +
	"\x06metric\x18\x04 \x01(\v2\x1c.node_agent.v1.MetricPayloadH\x00R\x06metric\x12N\n" +
	"\rhealth_result\x18\x05 \x01(\v2'.node_agent.v1.HealthCheckResultPayloadH\x00R\fhealthResult\x12F\n" +
	"\fprofile_data\x18\x06 \x01(\v2!.node_agent.v1.ProfileDataPayloadH\x00R\vprofileData\x12L\n" +
	"\x0econtainer_list\x18\a \x01(\v2#.node_agent.v1.ContainerListPayloadH\x00R\rcontainerList\x12L\n" +
	"\x0elog_diagnostic\x18\b \x01(\v2#.node_agent.v1.LogDiagnosticPayloadH\x00R\rlogDiagnostic\x12I\n" +
	"\rnetwork_stats\x18\t \x01(\v2\".node_agent.v1.NetworkStatsPayloadH\x00R\fnetworkStatsB\t\n" +
	"\apayload\"\xbe\x03\n" +
	"\rMetricPayload\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fram_total_bytes\x18\x02 \x01(\x04R\rramTotalBytes\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12.\n" +
	"\x13ram_available_bytes\x18\x04 \x01(\x04R\x11ramAvailableBytes\x12*\n" +
	"\x11ram_usage_percent\x18\x05 \x01(\x02R\x0framUsagePercent\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x120\n" +
	"\x14disk_available_bytes\x18\b \x01(\x04R\x12diskAvailableBytes\x12,\n" +
	"\x12disk_usage_percent\x18\t \x01(\x02R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x03R\ruptimeSeconds\"\xbe\x06\n" +
	"\rServerMessage\x12C\n" +
	"\vexecute_job\x18\x01 \x01(\v2 .node_agent.v1.ExecuteJobPayloadH\x00R\n" +
	"executeJob\x12C\n" +
	"\vstream_logs\x18\x02 \x01(\v2 .node_agent.v1.StreamLogsPayloadH\x00R\n" +
	"streamLogs\x12=\n" +
	"\tstop_logs\x18\x03 \x01(\v2\x1e.node_agent.v1.StopLogsPayloadH\x00R\bstopLogs\x12b\n" +
	"\x16configure_health_check\x18\x04 \x01(\v2*.node_agent.v1.ConfigureHealthCheckPayloadH\x00R\x14configureHealthCheck\x12S\n" +
	"\x11stop_health_check\x18\x05 \x01(\v2%.node_agent.v1.StopHealthCheckPayloadH\x00R\x0fstopHealthCheck\x12O\n" +
	"\x0frequest_profile\x18\x06 \x01(\v2$.node_agent.v1.RequestProfilePayloadH\x00R\x0erequestProfile\x12U\n" +
	"\x11stream_containers\x18\a \x01(\v2&.node_agent.v1.StreamContainersPayloadH\x00R\x10streamContainers\x12O\n" +
	"\x0fstop_containers\x18\b \x01(\v2$.node_agent.v1.StopContainersPayloadH\x00R\x0estopContainers\x12F\n" +
	"\fcollect_logs\x18\t \x01(\v2!.node_agent.v1.CollectLogsPayloadH\x00R\vcollectLogs\x12_\n" +
	"\x15request_network_stats\x18\n" +
	" \x01(\v2).node_agent.v1.RequestNetworkStatsPayloadH\x00R\x13requestNetworkStatsB\t\n" +
	"\apayload\"\x89\x01\n" +
	"\x10JobResultPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.node_agent.v1.JobStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"+\n" +
	"\x10HeartbeatPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa4\x01\n" +
	"\x11ExecuteJobPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12=\n" +
	"\fcommand_type\x18\x03 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\vcommandType\x12\x16\n" +
	"\x06params\x18\x04 \x01(\tR\x06params\"=\n" +
	"\x11StreamLogsPayload\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\"\x11\n" +
	"\x0fStopLogsPayload\"b\n" +
	"\x0fLogEntryPayload\x12!\n" +
	"\ftimestamp_us\x18\x01 \x01(\x03R\vtimestampUs\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc5\x03\n" +
	"\x1bConfigureHealthCheckPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x19\n" +
	"\bhttp_url\x18\x04 \x01(\tR\ahttpUrl\x120\n" +
	"\x14http_expected_status\x18\x05 \x01(\x05R\x12httpExpectedStatus\x12\x19\n" +
	"\btcp_host\x18\x06 \x01(\tR\atcpHost\x12\x19\n" +
	"\btcp_port\x18\a \x01(\x05R\atcpPort\x12)\n" +
	"\x10interval_seconds\x18\b \x01(\x05R\x0fintervalSeconds\x12+\n" +
	"\x11failure_threshold\x18\t \x01(\x05R\x10failureThreshold\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12(\n" +
	"\x10auto_heal_config\x18\v \x01(\tR\x0eautoHealConfig\x12&\n" +
	"\x0fauto_heal_state\x18\f \x01(\tR\rautoHealState\"7\n" +
	"\x16StopHealthCheckPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"\xe5\x01\n" +
	"\x18HealthCheckResultPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\x14consecutive_failures\x18\x05 \x01(\x05R\x13consecutiveFailures\x12&\n" +
	"\x0fauto_heal_state\x18\x06 \x01(\tR\rautoHealState\"\xa0\x01\n" +
	"\x15RequestProfilePayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12=\n" +
	"\fprofile_type\x18\x02 \x01(\x0e2\x1a.node_agent.v1.ProfileTypeR\vprofileType\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\"\x9c\x01\n" +
	"\x12ProfileDataPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12=\n" +
	"\fprofile_type\x18\x02 \x01(\x0e2\x1a.node_agent.v1.ProfileTypeR\vprofileType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x19\n" +
	"\x17StreamContainersPayload\"\x17\n" +
	"\x15StopContainersPayload\"\xb6\x01\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x10\n" +
	"\x03mem\x18\a \x01(\tR\x03mem\x12\x19\n" +
	"\bmem_perc\x18\b \x01(\tR\amemPerc\"j\n" +
	"\x14ContainerListPayload\x12<\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1c.node_agent.v1.ContainerInfoR\n" +
	"containers\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xbe\x03\n" +
	"\rMetricRequest\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fram_total_bytes\x18\x02 \x01(\x04R\rramTotalBytes\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12.\n" +
	"\x13ram_available_bytes\x18\x04 \x01(\x04R\x11ramAvailableBytes\x12*\n" +
	"\x11ram_usage_percent\x18\x05 \x01(\x02R\x0framUsagePercent\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x120\n" +
	"\x14disk_available_bytes\x18\b \x01(\x04R\x12diskAvailableBytes\x12,\n" +
	"\x12disk_usage_percent\x18\t \x01(\x02R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x03R\ruptimeSeconds\"*\n" +
	"\x0eMetricResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x12CollectLogsPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12(\n" +
	"\x10lines_per_source\x18\x03 \x01(\x05R\x0elinesPerSource\x12-\n" +
	"\x12include_containers\x18\x04 \x01(\bR\x11includeContainers\"\xae\x01\n" +
	"\x14LogDiagnosticPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fdiagnostic_json\x18\x02 \x01(\tR\x0ediagnosticJson\x128\n" +
	"\asources\x18\x03 \x03(\v2\x1e.node_agent.v1.LogSourceBundleR\asources\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"c\n" +
	"\x0fLogSourceBundle\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x19\n" +
	"\braw_logs\x18\x02 \x01(\tR\arawLogs\x12\x1d\n" +
	"\n" +
	"line_count\x18\x03 \x01(\x05R\tlineCount\";\n" +
	"\x1aRequestNetworkStatsPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"i\n" +
	"\x13NetworkStatsPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"stats_json\x18\x02 \x01(\tR\tstatsJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*v\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_DEFAULT\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_CUSTOM\x10\x01\x12\x1c\n" +
	"\x18COMMAND_TYPE_INSTALL_APP\x10\x02\x12\x16\n" +
	"\x12COMMAND_TYPE_SWARM\x10\x03*:\n" +
	"\vProfileType\x12\x15\n" +
	"\x11PROFILE_TYPE_HEAP\x10\x00\x12\x14\n" +
	"\x10PROFILE_TYPE_CPU\x10\x01*T\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x00\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x022\x8f\x02\n" +
	"\x10NodeAgentService\x12d\n" +
	"\x10RegisterCommands\x12%.node_agent.v1.RegisterCommandRequest\x1a'.node_agent.v1.RegisterCommandsResponse(\x01\x12G\n" +
	"\aConnect\x12\x1a.node_agent.v1.NodeMessage\x1a\x1c.node_agent.v1.ServerMessage(\x010\x01\x12L\n" +
	"\rReportMetrics\x12\x1c.node_agent.v1.MetricRequest\x1a\x1d.node_agent.v1.MetricResponseB;Z9github.com/arturo/autohost-cloud-api/internal/grpc/nodepbb\x06proto3"

var (
	file_proto_node_agent_v1_node_agent_proto_rawDescOnce sync.Once
	file_proto_node_agent_v1_node_agent_proto_rawDescData []byte
)

func file_proto_node_agent_v1_node_agent_proto_rawDescGZIP() []byte {
	file_proto_node_agent_v1_node_agent_proto_rawDescOnce.Do(func() {
		file_proto_node_agent_v1_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_agent_v1_node_agent_proto_rawDesc), len(file_proto_node_agent_v1_node_agent_proto_rawDesc)))
	})
	return file_proto_node_agent_v1_node_agent_proto_rawDescData
}

var file_proto_node_agent_v1_node_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_node_agent_v1_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_node_agent_v1_node_agent_proto_goTypes = []any{
	(CommandType)(0),                    // 0: node_agent.v1.CommandType
	(ProfileType)(0),                    // 1: node_agent.v1.ProfileType
	(JobStatus)(0),                      // 2: node_agent.v1.JobStatus
	(*RegisterCommandRequest)(nil),      // 3: node_agent.v1.RegisterCommandRequest
	(*RegisterCommandsResponse)(nil),    // 4: node_agent.v1.RegisterCommandsResponse
	(*NodeMessage)(nil),                 // 5: node_agent.v1.NodeMessage
	(*MetricPayload)(nil),               // 6: node_agent.v1.MetricPayload
	(*ServerMessage)(nil),               // 7: node_agent.v1.ServerMessage
	(*JobResultPayload)(nil),            // 8: node_agent.v1.JobResultPayload
	(*HeartbeatPayload)(nil),            // 9: node_agent.v1.HeartbeatPayload
	(*ExecuteJobPayload)(nil),           // 10: node_agent.v1.ExecuteJobPayload
	(*StreamLogsPayload)(nil),           // 11: node_agent.v1.StreamLogsPayload
	(*StopLogsPayload)(nil),             // 12: node_agent.v1.StopLogsPayload
	(*LogEntryPayload)(nil),             // 13: node_agent.v1.LogEntryPayload
	(*ConfigureHealthCheckPayload)(nil), // 14: node_agent.v1.ConfigureHealthCheckPayload
	(*StopHealthCheckPayload)(nil),      // 15: node_agent.v1.StopHealthCheckPayload
	(*HealthCheckResultPayload)(nil),    // 16: node_agent.v1.HealthCheckResultPayload
	(*RequestProfilePayload)(nil),       // 17: node_agent.v1.RequestProfilePayload
	(*ProfileDataPayload)(nil),          // 18: node_agent.v1.ProfileDataPayload
	(*StreamContainersPayload)(nil),     // 19: node_agent.v1.StreamContainersPayload
	(*StopContainersPayload)(nil),       // 20: node_agent.v1.StopContainersPayload
	(*ContainerInfo)(nil),               // 21: node_agent.v1.ContainerInfo
	(*ContainerListPayload)(nil),        // 22: node_agent.v1.ContainerListPayload
	(*MetricRequest)(nil),               // 23: node_agent.v1.MetricRequest
	(*MetricResponse)(nil),              // 24: node_agent.v1.MetricResponse
	(*CollectLogsPayload)(nil),          // 25: node_agent.v1.CollectLogsPayload
	(*LogDiagnosticPayload)(nil),        // 26: node_agent.v1.LogDiagnosticPayload
	(*LogSourceBundle)(nil),             // 27: node_agent.v1.LogSourceBundle
	(*RequestNetworkStatsPayload)(nil),  // 28: node_agent.v1.RequestNetworkStatsPayload
	(*NetworkStatsPayload)(nil),         // 29: node_agent.v1.NetworkStatsPayload
}
var file_proto_node_agent_v1_node_agent_proto_depIdxs = []int32{
	0,  // 0: node_agent.v1.RegisterCommandRequest.type:type_name -> node_agent.v1.CommandType
	8,  // 1: node_agent.v1.NodeMessage.job_result:type_name -> node_agent.v1.JobResultPayload
	9,  // 2: node_agent.v1.NodeMessage.heartbeat:type_name -> node_agent.v1.HeartbeatPayload
	13, // 3: node_agent.v1.NodeMessage.log_entry:type_name -> node_agent.v1.LogEntryPayload
	6,  // 4: node_agent.v1.NodeMessage.metric:type_name -> node_agent.v1.MetricPayload
	16, // 5: node_agent.v1.NodeMessage.health_result:type_name -> node_agent.v1.HealthCheckResultPayload
	18, // 6: node_agent.v1.NodeMessage.profile_data:type_name -> node_agent.v1.ProfileDataPayload
	22, // 7: node_agent.v1.NodeMessage.container_list:type_name -> node_agent.v1.ContainerListPayload
	26, // 8: node_agent.v1.NodeMessage.log_diagnostic:type_name -> node_agent.v1.LogDiagnosticPayload
	29, // 9: node_agent.v1.NodeMessage.network_stats:type_name -> node_agent.v1.NetworkStatsPayload
	10, // 10: node_agent.v1.ServerMessage.execute_job:type_name -> node_agent.v1.ExecuteJobPayload
	11, // 11: node_agent.v1.ServerMessage.stream_logs:type_name -> node_agent.v1.StreamLogsPayload
	12, // 12: node_agent.v1.ServerMessage.stop_logs:type_name -> node_agent.v1.StopLogsPayload
	14, // 13: node_agent.v1.ServerMessage.configure_health_check:type_name -> node_agent.v1.ConfigureHealthCheckPayload
	15, // 14: node_agent.v1.ServerMessage.stop_health_check:type_name -> node_agent.v1.StopHealthCheckPayload
	17, // 15: node_agent.v1.ServerMessage.request_profile:type_name -> node_agent.v1.RequestProfilePayload
	19, // 16: node_agent.v1.ServerMessage.stream_containers:type_name -> node_agent.v1.StreamContainersPayload
	20, // 17: node_agent.v1.ServerMessage.stop_containers:type_name -> node_agent.v1.StopContainersPayload
	25, // 18: node_agent.v1.ServerMessage.collect_logs:type_name -> node_agent.v1.CollectLogsPayload
	28, // 19: node_agent.v1.ServerMessage.request_network_stats:type_name -> node_agent.v1.RequestNetworkStatsPayload
	2,  // 20: node_agent.v1.JobResultPayload.status:type_name -> node_agent.v1.JobStatus
	0,  // 21: node_agent.v1.ExecuteJobPayload.command_type:type_name -> node_agent.v1.CommandType
	1,  // 22: node_agent.v1.RequestProfilePayload.profile_type:type_name -> node_agent.v1.ProfileType
	1,  // 23: node_agent.v1.ProfileDataPayload.profile_type:type_name -> node_agent.v1.ProfileType
	21, // 24: node_agent.v1.ContainerListPayload.containers:type_name -> node_agent.v1.ContainerInfo
	27, // 25: node_agent.v1.LogDiagnosticPayload.sources:type_name -> node_agent.v1.LogSourceBundle
	3,  // 26: node_agent.v1.NodeAgentService.RegisterCommands:input_type -> node_agent.v1.RegisterCommandRequest
	5,  // 27: node_agent.v1.NodeAgentService.Connect:input_type -> node_agent.v1.NodeMessage
	23, // 28: node_agent.v1.NodeAgentService.ReportMetrics:input_type -> node_agent.v1.MetricRequest
	4,  // 29: node_agent.v1.NodeAgentService.RegisterCommands:output_type -> node_agent.v1.RegisterCommandsResponse
	7,  // 30: node_agent.v1.NodeAgentService.Connect:output_type -> node_agent.v1.ServerMessage
	24, // 31: node_agent.v1.NodeAgentService.ReportMetrics:output_type -> node_agent.v1.MetricResponse
	29, // [29:32] is the sub-list for method output_type
	26, // [26:29] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_node_agent_v1_node_agent_proto_init() }
func file_proto_node_agent_v1_node_agent_proto_init() {
	if File_proto_node_agent_v1_node_agent_proto != nil {
		return
	}
	file_proto_node_agent_v1_node_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_JobResult)(nil),
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_LogEntry)(nil),
		(*NodeMessage_Metric)(nil),
		(*NodeMessage_HealthResult)(nil),
		(*NodeMessage_ProfileData)(nil),
		(*NodeMessage_ContainerList)(nil),
		(*NodeMessage_LogDiagnostic)(nil),
		(*NodeMessage_NetworkStats)(nil),
	}
	file_proto_node_agent_v1_node_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_ExecuteJob)(nil),
		(*ServerMessage_StreamLogs)(nil),
		(*ServerMessage_StopLogs)(nil),
		(*ServerMessage_ConfigureHealthCheck)(nil),
		(*ServerMessage_StopHealthCheck)(nil),
		(*ServerMessage_RequestProfile)(nil),
		(*ServerMessage_StreamContainers)(nil),
		(*ServerMessage_StopContainers)(nil),
		(*ServerMessage_CollectLogs)(nil),
		(*ServerMessage_RequestNetworkStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_agent_v1_node_agent_proto_rawDesc), len(file_proto_node_agent_v1_node_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_agent_v1_node_agent_proto_goTypes,
		DependencyIndexes: file_proto_node_agent_v1_node_agent_proto_depIdxs,
		EnumInfos:         file_proto_node_agent_v1_node_agent_proto_enumTypes,
		MessageInfos:      file_proto_node_agent_v1_node_agent_proto_msgTypes,
	}.Build()
	File_proto_node_agent_v1_node_agent_proto = out.File
	file_proto_node_agent_v1_node_agent_proto_goTypes = nil
	file_proto_node_agent_v1_node_agent_proto_depIdxs = nil
}
